# Generated by Django 5.2.5 on 2025-09-02 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="店铺名称")),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shop_icons/",
                        verbose_name="店铺图标",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="店铺电话")),
                ("address", models.TextField(verbose_name="店铺地址")),
                (
                    "activity",
                    models.TextField(blank=True, null=True, verbose_name="店铺活动"),
                ),
                (
                    "business_hours",
                    models.CharField(max_length=100, verbose_name="营业时间"),
                ),
                ("is_open", models.BooleanField(default=True, verbose_name="是否营业")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "店铺",
                "verbose_name_plural": "店铺",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShopCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="分类描述"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="category_icons/",
                        verbose_name="分类图标",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "店铺分类",
                "verbose_name_plural": "店铺分类",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100, verbose_name="食品分类")),
                ("name", models.CharField(max_length=200, verbose_name="食品名称")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="food_images/",
                        verbose_name="食品图片",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="食品价格"
                    ),
                ),
                (
                    "purchase_count",
                    models.IntegerField(default=0, verbose_name="购买数量"),
                ),
                ("is_new", models.BooleanField(default=False, verbose_name="是否新品")),
                ("is_hot", models.BooleanField(default=False, verbose_name="是否热门")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="食品描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foods",
                        to="shop.shop",
                        verbose_name="所属店铺",
                    ),
                ),
            ],
            options={
                "verbose_name": "食品",
                "verbose_name_plural": "食品",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="shop",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shops",
                to="shop.shopcategory",
                verbose_name="店铺分类",
            ),
        ),
    ]
